// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Lang1000 from "../src/Lang1000.res.mjs";

Vitest.describe("Lang1000.Config", (function () {
        Vitest.test("version is defined", (function () {
                Vitest.expect(Lang1000.Config.version).toBe("0.1.0");
              }));
        Vitest.test("name is correct", (function () {
                Vitest.expect(Lang1000.Config.name).toBe("1000Langs");
              }));
        Vitest.test("allSources contains expected sources", (function () {
                var sources = Lang1000.Config.allSources;
                Vitest.expect(sources.length).toBe(6);
              }));
        Vitest.test("sourceToString converts correctly", (function () {
                Vitest.expect(Lang1000.Config.sourceToString("BibleCloud")).toBe("bible.cloud");
                Vitest.expect(Lang1000.Config.sourceToString("BibleCom")).toBe("bible.com");
                Vitest.expect(Lang1000.Config.sourceToString("PngScriptures")).toBe("pngscriptures.org");
              }));
      }));

Vitest.describe("Lang1000.Language", (function () {
        Vitest.test("make creates a language with required fields", (function () {
                var lang = Lang1000.Language.make("eng", "English", undefined, undefined, undefined, undefined);
                Vitest.expect(Lang1000.Language.getCode(lang)).toBe("eng");
                Vitest.expect(Lang1000.Language.getName(lang)).toBe("English");
              }));
        Vitest.test("make creates a language with optional fields", (function () {
                var lang = Lang1000.Language.make("deu", "German", "Indo-European", "Latin", "Germany", undefined);
                Vitest.expect(lang.family).toEqual("Indo-European");
                Vitest.expect(lang.script).toEqual("Latin");
                Vitest.expect(lang.country).toEqual("Germany");
              }));
      }));

Vitest.describe("Lang1000.Verse", (function () {
        Vitest.test("makeReference creates a valid reference", (function () {
                var ref = Lang1000.Verse.makeReference("GEN", 1, 1);
                Vitest.expect(ref.book).toBe("GEN");
                Vitest.expect(ref.chapter).toBe(1);
                Vitest.expect(ref.verse).toBe(1);
              }));
        Vitest.test("toCanonicalId formats correctly", (function () {
                var ref = Lang1000.Verse.makeReference("GEN", 1, 1);
                Vitest.expect(Lang1000.Verse.toCanonicalId(ref)).toBe("GEN.1.1");
              }));
        Vitest.test("toCanonicalId handles multi-digit chapters and verses", (function () {
                var ref = Lang1000.Verse.makeReference("PSA", 119, 176);
                Vitest.expect(Lang1000.Verse.toCanonicalId(ref)).toBe("PSA.119.176");
              }));
      }));

Vitest.describe("Lang1000.Corpus", (function () {
        Vitest.test("empty creates an empty corpus", (function () {
                var corpus = Lang1000.Corpus.empty("TestCorpus");
                Vitest.expect(corpus.name).toBe("TestCorpus");
                Vitest.expect(Lang1000.Corpus.languageCount(corpus)).toBe(0);
                Vitest.expect(Lang1000.Corpus.alignmentCount(corpus)).toBe(0);
              }));
        Vitest.test("addLanguage increases language count", (function () {
                var corpus = Lang1000.Corpus.empty("TestCorpus");
                var lang = Lang1000.Language.make("eng", "English", undefined, undefined, undefined, undefined);
                var updated = Lang1000.Corpus.addLanguage(corpus, lang);
                Vitest.expect(Lang1000.Corpus.languageCount(updated)).toBe(1);
              }));
        Vitest.test("addAlignment increases alignment count", (function () {
                var corpus = Lang1000.Corpus.empty("TestCorpus");
                var alignment_translations = {};
                var alignment = {
                  referenceId: "GEN.1.1",
                  translations: alignment_translations
                };
                var updated = Lang1000.Corpus.addAlignment(corpus, alignment);
                Vitest.expect(Lang1000.Corpus.alignmentCount(updated)).toBe(1);
              }));
      }));

export {
  
}
/*  Not a pure module */
