# SPDX-License-Identifier: MIT AND LicenseRef-Palimpsest-0.8
# SPDX-FileCopyrightText: 2024-2025 Ehsaneddin Asgari and Contributors
#
# Funding information for 1000Langs
# ==================================
# These are supported funding model platforms

github: []
patreon: # Replace with actual patreon username
open_collective: # Replace with actual open_collective username
ko_fi: # Replace with actual ko_fi username
tidelift: # Replace with actual tidelift package/platform
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-hierarchical-namespace-controller
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-hierarchical-namespace-controller
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
