// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Crawler from "./Crawler.res.mjs";

var baseUrl = "https://www.bible.com";

var Config = {
  baseUrl: baseUrl,
  apiUrl: "https://www.bible.com/api/bible"
};

function versions() {
  return baseUrl + "/versions";
}

function version(versionId) {
  return baseUrl + "/versions/" + versionId.toString();
}

function bible(versionId, bookCode, chapter) {
  return baseUrl + "/bible/" + versionId.toString() + "/" + bookCode + "." + chapter.toString();
}

function search(versionId, query) {
  return baseUrl + "/search/bible?version_id=" + versionId.toString() + "&q=" + query;
}

var Endpoints = {
  versions: versions,
  version: version,
  bible: bible,
  search: search
};

var Selectors = {
  verseContainer: ".ChapterContent_verse__uvbXo",
  verseNumber: ".ChapterContent_label__R2PLt",
  verseText: ".ChapterContent_content__RlRwn",
  chapterNav: ".ChapterContent_nav__vVPwy",
  versionSelector: ".VersionSelector_container__3uKjR"
};

var Types = {};

function parseVersionList(_html) {
  return "NoMatch";
}

function parseChapter(_html) {
  return "NoMatch";
}

function extractVerseText(_element) {
  
}

function normalizeText(text) {
  return text.trim().replace(/\s+/g, " ");
}

var Parser = {
  parseVersionList: parseVersionList,
  parseChapter: parseChapter,
  extractVerseText: extractVerseText,
  normalizeText: normalizeText
};

function make() {
  return {
          rateLimiter: Crawler.RateLimiter.make(1000, undefined),
          state: "Idle",
          cachedVersions: undefined
        };
}

function fetchVersions(_crawler) {
  return "Pending";
}

function fetchChapter(_crawler, _versionId, _book, _chapter) {
  return "Pending";
}

function fetchBook(_crawler, _versionId, _book) {
  return "Pending";
}

var Crawler$1 = {
  make: make,
  fetchVersions: fetchVersions,
  fetchChapter: fetchChapter,
  fetchBook: fetchBook
};

export {
  Config ,
  Endpoints ,
  Selectors ,
  Types ,
  Parser ,
  Crawler$1 as Crawler,
}
/* No side effect */
