// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Crawler from "./Crawler.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var baseUrl = "https://api.scripture.api.bible/v1";

var Config = {
  baseUrl: baseUrl,
  webUrl: "https://bible.cloud",
  apiVersion: "v1"
};

function bibles() {
  return baseUrl + "/bibles";
}

function bible(bibleId) {
  return baseUrl + "/bibles/" + bibleId;
}

function books(bibleId) {
  return baseUrl + "/bibles/" + bibleId + "/books";
}

function chapters(bibleId, bookId) {
  return baseUrl + "/bibles/" + bibleId + "/books/" + bookId + "/chapters";
}

function verses(bibleId, chapterId) {
  return baseUrl + "/bibles/" + bibleId + "/chapters/" + chapterId + "/verses";
}

function verse(bibleId, verseId) {
  return baseUrl + "/bibles/" + bibleId + "/verses/" + verseId;
}

var Endpoints = {
  bibles: bibles,
  bible: bible,
  books: books,
  chapters: chapters,
  verses: verses,
  verse: verse
};

var Types = {};

function parseBibleList(_json) {
  return "NoMatch";
}

function parseBooks(_json) {
  return "NoMatch";
}

function parseChapters(_json) {
  return "NoMatch";
}

function parseVerseText(_html) {
  return "NoMatch";
}

var Parser = {
  parseBibleList: parseBibleList,
  parseBooks: parseBooks,
  parseChapters: parseChapters,
  parseVerseText: parseVerseText
};

function make(apiKey, param) {
  return {
          credentials: Core__Option.map(apiKey, (function (key) {
                  return {
                          apiKey: key,
                          apiSecret: undefined
                        };
                })),
          rateLimiter: Crawler.RateLimiter.make(500, undefined),
          state: "Idle"
        };
}

function fetchBibles(_crawler) {
  return "Pending";
}

function fetchBooks(_crawler, _bibleId) {
  return "Pending";
}

function fetchChapter(_crawler, _bibleId, _chapterId) {
  return "Pending";
}

var Crawler$1 = {
  make: make,
  fetchBibles: fetchBibles,
  fetchBooks: fetchBooks,
  fetchChapter: fetchChapter
};

export {
  Config ,
  Endpoints ,
  Types ,
  Parser ,
  Crawler$1 as Crawler,
}
/* No side effect */
