// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Crawler from "./Crawler.res.mjs";

var baseUrl = "https://pngscriptures.org";

var downloadUrl = "https://pngscriptures.org/download";

var Config = {
  baseUrl: baseUrl,
  downloadUrl: downloadUrl
};

function languages() {
  return baseUrl + "/languages";
}

function language(langCode) {
  return baseUrl + "/lng/" + langCode;
}

function download(langCode, format) {
  var formatStr;
  switch (format) {
    case "Zip" :
        formatStr = "zip";
        break;
    case "Pdf" :
        formatStr = "pdf";
        break;
    case "Epub" :
        formatStr = "epub";
        break;
    case "Html" :
        formatStr = "html";
        break;
    
  }
  return downloadUrl + "/" + langCode + "/" + formatStr;
}

var Endpoints = {
  languages: languages,
  language: language,
  download: download
};

var Types = {};

function parseLanguageList(_html) {
  return "NoMatch";
}

function parseZipContents(_archive) {
  return "NoMatch";
}

function parseHtmlBook(_html) {
  return "NoMatch";
}

var Parser = {
  parseLanguageList: parseLanguageList,
  parseZipContents: parseZipContents,
  parseHtmlBook: parseHtmlBook
};

function make(downloadDirOpt, param) {
  var downloadDir = downloadDirOpt !== undefined ? downloadDirOpt : "./downloads/png";
  return {
          rateLimiter: Crawler.RateLimiter.make(2000, undefined),
          state: "Idle",
          downloadDir: downloadDir
        };
}

function fetchLanguages(_crawler) {
  return "Pending";
}

function downloadTranslation(_crawler, _langCode, _format) {
  return "Pending";
}

function extractAndParse(_crawler, _zipPath) {
  return "Pending";
}

var Crawler$1 = {
  make: make,
  fetchLanguages: fetchLanguages,
  downloadTranslation: downloadTranslation,
  extractAndParse: extractAndParse
};

export {
  Config ,
  Endpoints ,
  Types ,
  Parser ,
  Crawler$1 as Crawler,
}
/* No side effect */
