// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Crawler from "../crawlers/Crawler.res.mjs";

var apiBaseUrl = "https://api.scripture.api.bible/v1";

function getBaseUrl(env) {
  if (env === "Production") {
    return apiBaseUrl;
  } else {
    return "https://api-sandbox.scripture.api.bible/v1";
  }
}

var Config = {
  apiBaseUrl: apiBaseUrl,
  cdnBaseUrl: "https://cdn.scripture.api.bible",
  getBaseUrl: getBaseUrl
};

var Types = {};

function make(apiKey, environmentOpt, param) {
  var environment = environmentOpt !== undefined ? environmentOpt : "Production";
  return {
          apiKey: apiKey,
          environment: environment,
          rateLimiter: Crawler.RateLimiter.make(100, undefined)
        };
}

function getAuthHeaders(client) {
  var headers = {};
  headers["api-key"] = client.apiKey;
  headers["Accept"] = "application/json";
  return headers;
}

function getBibles(_client, language, abbreviation, param) {
  return Promise.resolve({
              TAG: "Error",
              _0: {
                statusCode: 501,
                error: "NotImplemented",
                message: "TODO"
              }
            });
}

function getBible(_client, bibleId) {
  return Promise.resolve({
              TAG: "Error",
              _0: {
                statusCode: 501,
                error: "NotImplemented",
                message: "TODO"
              }
            });
}

function getBooks(_client, bibleId) {
  return Promise.resolve({
              TAG: "Error",
              _0: {
                statusCode: 501,
                error: "NotImplemented",
                message: "TODO"
              }
            });
}

function getChapters(_client, bibleId, bookId) {
  return Promise.resolve({
              TAG: "Error",
              _0: {
                statusCode: 501,
                error: "NotImplemented",
                message: "TODO"
              }
            });
}

function getVerses(_client, bibleId, chapterId) {
  return Promise.resolve({
              TAG: "Error",
              _0: {
                statusCode: 501,
                error: "NotImplemented",
                message: "TODO"
              }
            });
}

function getPassage(_client, bibleId, passageId) {
  return Promise.resolve({
              TAG: "Error",
              _0: {
                statusCode: 501,
                error: "NotImplemented",
                message: "TODO"
              }
            });
}

var Client = {
  make: make,
  getAuthHeaders: getAuthHeaders,
  getBibles: getBibles,
  getBible: getBible,
  getBooks: getBooks,
  getChapters: getChapters,
  getVerses: getVerses,
  getPassage: getPassage
};

export {
  Config ,
  Types ,
  Client ,
}
/* No side effect */
