// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Crawler from "../../src/crawlers/Crawler.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

Vitest.describe("Crawler.Config", (function () {
        Vitest.test("has sensible default timeout", (function () {
                Vitest.expect(Crawler.Config.defaultTimeout).toBe(30000);
              }));
        Vitest.test("has sensible default retries", (function () {
                Vitest.expect(Crawler.Config.defaultRetries).toBe(3);
              }));
        Vitest.test("has sensible default rate limit", (function () {
                Vitest.expect(Crawler.Config.defaultRateLimitMs).toBe(1000);
              }));
        Vitest.test("makeDefaultHeaders creates valid headers", (function () {
                var headers = Crawler.Config.makeDefaultHeaders();
                var userAgent = headers["User-Agent"];
                Vitest.expect(Core__Option.isSome(userAgent)).toBe(true);
              }));
      }));

Vitest.describe("Crawler.Request", (function () {
        Vitest.test("make creates request with defaults", (function () {
                var req = Crawler.$$Request.make("https://example.com", undefined, undefined, undefined, undefined, undefined);
                Vitest.expect(req.url).toBe("https://example.com");
                Vitest.expect(req.method).toEqual("GET");
                Vitest.expect(req.timeout).toBe(Crawler.Config.defaultTimeout);
                Vitest.expect(req.retries).toBe(Crawler.Config.defaultRetries);
              }));
        Vitest.test("make accepts custom options", (function () {
                var req = Crawler.$$Request.make("https://example.com", "POST", undefined, 5000, 5, undefined);
                Vitest.expect(req.method).toEqual("POST");
                Vitest.expect(req.timeout).toBe(5000);
                Vitest.expect(req.retries).toBe(5);
              }));
        Vitest.test("withHeader adds header", (function () {
                var req = Crawler.$$Request.make("https://example.com", undefined, undefined, undefined, undefined, undefined);
                Crawler.$$Request.withHeader(req, "X-Custom", "value");
                Vitest.expect(req.headers["X-Custom"]).toEqual("value");
              }));
        Vitest.test("methodToString converts correctly", (function () {
                Vitest.expect(Crawler.$$Request.methodToString("GET")).toBe("GET");
                Vitest.expect(Crawler.$$Request.methodToString("POST")).toBe("POST");
                Vitest.expect(Crawler.$$Request.methodToString("HEAD")).toBe("HEAD");
              }));
      }));

Vitest.describe("Crawler.RateLimiter", (function () {
        Vitest.test("make creates limiter with default delay", (function () {
                var limiter = Crawler.RateLimiter.make(undefined, undefined);
                Vitest.expect(limiter.delayMs).toBe(Crawler.Config.defaultRateLimitMs);
              }));
        Vitest.test("make accepts custom delay", (function () {
                var limiter = Crawler.RateLimiter.make(2000, undefined);
                Vitest.expect(limiter.delayMs).toBe(2000);
              }));
        Vitest.test("canProceed returns true for new limiter", (function () {
                var limiter = Crawler.RateLimiter.make(undefined, undefined);
                Vitest.expect(Crawler.RateLimiter.canProceed(limiter)).toBe(true);
              }));
        Vitest.test("recordRequest updates lastRequest", (function () {
                var limiter = Crawler.RateLimiter.make(undefined, undefined);
                var before = limiter.lastRequest;
                Crawler.RateLimiter.recordRequest(limiter);
                Vitest.expect(limiter.lastRequest > before).toBe(true);
              }));
      }));

Vitest.describe("Crawler.RetryPolicy", (function () {
        Vitest.describe("calculateDelay", (function () {
                Vitest.test("Constant returns same delay", (function () {
                        var strategy = {
                          TAG: "Constant",
                          _0: 1000
                        };
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 1)).toBe(1000);
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 3)).toBe(1000);
                      }));
                Vitest.test("Linear increases linearly", (function () {
                        var strategy = {
                          TAG: "Linear",
                          _0: 1000
                        };
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 1)).toBe(1000);
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 2)).toBe(2000);
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 3)).toBe(3000);
                      }));
                Vitest.test("Exponential increases exponentially", (function () {
                        var strategy = {
                          TAG: "Exponential",
                          _0: 1000,
                          _1: 2.0
                        };
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 1)).toBe(1000);
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 2)).toBe(2000);
                        Vitest.expect(Crawler.RetryPolicy.calculateDelay(strategy, 3)).toBe(4000);
                      }));
              }));
        Vitest.describe("shouldRetry", (function () {
                Vitest.test("returns true when under max", (function () {
                        Vitest.expect(Crawler.RetryPolicy.shouldRetry(1, 3)).toBe(true);
                        Vitest.expect(Crawler.RetryPolicy.shouldRetry(2, 3)).toBe(true);
                      }));
                Vitest.test("returns false when at or over max", (function () {
                        Vitest.expect(Crawler.RetryPolicy.shouldRetry(3, 3)).toBe(false);
                        Vitest.expect(Crawler.RetryPolicy.shouldRetry(4, 3)).toBe(false);
                      }));
              }));
      }));

Vitest.describe("Crawler.Parser", (function () {
        Vitest.test("selectorToString formats correctly", (function () {
                Vitest.expect(Crawler.Parser.selectorToString({
                            TAG: "Css",
                            _0: ".verse"
                          })).toBe("css:.verse");
                Vitest.expect(Crawler.Parser.selectorToString({
                            TAG: "XPath",
                            _0: "//div"
                          })).toBe("xpath://div");
                Vitest.expect(Crawler.Parser.selectorToString({
                            TAG: "Regex",
                            _0: "\\d+"
                          })).toBe("regex:\\d+");
              }));
      }));

export {
  
}
/*  Not a pure module */
