// Generated by ReScript, PLEASE EDIT WITH CARE


var Types = {};

var iso639_1Pattern = /^[a-z]{2}$/;

var iso639_3Pattern = /^[a-z]{3}$/;

function isValidIso639_1(code) {
  return iso639_1Pattern.test(code);
}

function isValidIso639_3(code) {
  return iso639_3Pattern.test(code);
}

function detectCodeType(code) {
  var len = code.length;
  if (len !== 2) {
    if (len !== 3 || !iso639_3Pattern.test(code)) {
      return ;
    } else {
      return "Iso639_3";
    }
  } else if (iso639_1Pattern.test(code)) {
    return "Iso639_1";
  } else {
    return ;
  }
}

function normalize(code) {
  return code.toLowerCase().trim();
}

var Validation = {
  iso639_1Pattern: iso639_1Pattern,
  iso639_3Pattern: iso639_3Pattern,
  isValidIso639_1: isValidIso639_1,
  isValidIso639_3: isValidIso639_3,
  detectCodeType: detectCodeType,
  normalize: normalize
};

var undetermined = "und";

var multiple = "mul";

var miscellaneous = "mis";

var noLinguistic = "zxx";

function isSpecial(code) {
  if (code === undetermined || code === multiple || code === miscellaneous) {
    return true;
  } else {
    return code === noLinguistic;
  }
}

var SpecialCodes = {
  undetermined: undetermined,
  multiple: multiple,
  miscellaneous: miscellaneous,
  noLinguistic: noLinguistic,
  isSpecial: isSpecial
};

var d = {};

d["en"] = "eng";

d["de"] = "deu";

d["fr"] = "fra";

d["es"] = "spa";

d["it"] = "ita";

d["pt"] = "por";

d["ru"] = "rus";

d["zh"] = "zho";

d["ja"] = "jpn";

d["ko"] = "kor";

d["ar"] = "ara";

d["he"] = "heb";

d["el"] = "ell";

d["la"] = "lat";

function toIso639_3(code) {
  var normalized = code.toLowerCase().trim();
  var match = detectCodeType(normalized);
  if (match === undefined) {
    return ;
  }
  switch (match) {
    case "Iso639_1" :
        return d[normalized];
    case "Iso639_2b" :
    case "Iso639_2t" :
        return ;
    case "Iso639_3" :
        return normalized;
    
  }
}

var Conversion = {
  iso1ToIso3: d,
  toIso639_3: toIso639_3
};

function empty() {
  return {
          byIso3: {},
          byIso1: {},
          byName: {}
        };
}

function add(registry, entry) {
  registry.byIso3[entry.iso639_3] = entry;
  var code = entry.iso639_1;
  if (code !== undefined) {
    registry.byIso1[code] = entry;
  }
  registry.byName[entry.name.toLowerCase()] = entry;
}

function findByCode(registry, code) {
  var normalized = code.toLowerCase().trim();
  var match = detectCodeType(normalized);
  if (match !== undefined) {
    if (match === "Iso639_1") {
      return registry.byIso1[normalized];
    } else {
      return registry.byIso3[normalized];
    }
  }
  
}

function findByName(registry, name) {
  return registry.byName[name.toLowerCase()];
}

function count(registry) {
  return Object.keys(registry.byIso3).length;
}

var Registry = {
  empty: empty,
  add: add,
  findByCode: findByCode,
  findByName: findByName,
  count: count
};

export {
  Types ,
  Validation ,
  SpecialCodes ,
  Conversion ,
  Registry ,
}
/*  Not a pure module */
