// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Iso639 from "../../src/utils/Iso639.res.mjs";
import * as Vitest from "vitest";

Vitest.describe("Iso639.Validation", (function () {
        Vitest.describe("isValidIso639_1", (function () {
                Vitest.test("returns true for valid 2-letter codes", (function () {
                        Vitest.expect(Iso639.Validation.isValidIso639_1("en")).toBe(true);
                        Vitest.expect(Iso639.Validation.isValidIso639_1("de")).toBe(true);
                        Vitest.expect(Iso639.Validation.isValidIso639_1("zh")).toBe(true);
                      }));
                Vitest.test("returns false for invalid codes", (function () {
                        Vitest.expect(Iso639.Validation.isValidIso639_1("eng")).toBe(false);
                        Vitest.expect(Iso639.Validation.isValidIso639_1("e")).toBe(false);
                        Vitest.expect(Iso639.Validation.isValidIso639_1("EN")).toBe(false);
                        Vitest.expect(Iso639.Validation.isValidIso639_1("")).toBe(false);
                      }));
              }));
        Vitest.describe("isValidIso639_3", (function () {
                Vitest.test("returns true for valid 3-letter codes", (function () {
                        Vitest.expect(Iso639.Validation.isValidIso639_3("eng")).toBe(true);
                        Vitest.expect(Iso639.Validation.isValidIso639_3("deu")).toBe(true);
                        Vitest.expect(Iso639.Validation.isValidIso639_3("zho")).toBe(true);
                      }));
                Vitest.test("returns false for invalid codes", (function () {
                        Vitest.expect(Iso639.Validation.isValidIso639_3("en")).toBe(false);
                        Vitest.expect(Iso639.Validation.isValidIso639_3("english")).toBe(false);
                        Vitest.expect(Iso639.Validation.isValidIso639_3("ENG")).toBe(false);
                        Vitest.expect(Iso639.Validation.isValidIso639_3("")).toBe(false);
                      }));
              }));
        Vitest.describe("detectCodeType", (function () {
                Vitest.test("detects ISO 639-1 codes", (function () {
                        Vitest.expect(Iso639.Validation.detectCodeType("en")).toEqual("Iso639_1");
                      }));
                Vitest.test("detects ISO 639-3 codes", (function () {
                        Vitest.expect(Iso639.Validation.detectCodeType("eng")).toEqual("Iso639_3");
                      }));
                Vitest.test("returns None for invalid codes", (function () {
                        Vitest.expect(Iso639.Validation.detectCodeType("english")).toEqual(undefined);
                        Vitest.expect(Iso639.Validation.detectCodeType("")).toEqual(undefined);
                      }));
              }));
        Vitest.describe("normalize", (function () {
                Vitest.test("converts to lowercase", (function () {
                        Vitest.expect(Iso639.Validation.normalize("ENG")).toBe("eng");
                        Vitest.expect(Iso639.Validation.normalize("EN")).toBe("en");
                      }));
                Vitest.test("trims whitespace", (function () {
                        Vitest.expect(Iso639.Validation.normalize(" eng ")).toBe("eng");
                      }));
              }));
      }));

Vitest.describe("Iso639.SpecialCodes", (function () {
        Vitest.test("isSpecial returns true for special codes", (function () {
                Vitest.expect(Iso639.SpecialCodes.isSpecial("und")).toBe(true);
                Vitest.expect(Iso639.SpecialCodes.isSpecial("mul")).toBe(true);
                Vitest.expect(Iso639.SpecialCodes.isSpecial("mis")).toBe(true);
                Vitest.expect(Iso639.SpecialCodes.isSpecial("zxx")).toBe(true);
              }));
        Vitest.test("isSpecial returns false for regular codes", (function () {
                Vitest.expect(Iso639.SpecialCodes.isSpecial("eng")).toBe(false);
                Vitest.expect(Iso639.SpecialCodes.isSpecial("deu")).toBe(false);
              }));
      }));

Vitest.describe("Iso639.Conversion", (function () {
        Vitest.describe("toIso639_3", (function () {
                Vitest.test("converts ISO 639-1 to ISO 639-3", (function () {
                        Vitest.expect(Iso639.Conversion.toIso639_3("en")).toEqual("eng");
                        Vitest.expect(Iso639.Conversion.toIso639_3("de")).toEqual("deu");
                        Vitest.expect(Iso639.Conversion.toIso639_3("fr")).toEqual("fra");
                      }));
                Vitest.test("passes through valid ISO 639-3 codes", (function () {
                        Vitest.expect(Iso639.Conversion.toIso639_3("eng")).toEqual("eng");
                      }));
                Vitest.test("returns None for unknown codes", (function () {
                        Vitest.expect(Iso639.Conversion.toIso639_3("xx")).toEqual(undefined);
                      }));
              }));
      }));

Vitest.describe("Iso639.Registry", (function () {
        Vitest.test("empty creates empty registry", (function () {
                var registry = Iso639.Registry.empty();
                Vitest.expect(Iso639.Registry.count(registry)).toBe(0);
              }));
        Vitest.test("add and findByCode works", (function () {
                var registry = Iso639.Registry.empty();
                var entry = {
                  iso639_3: "eng",
                  iso639_2b: "eng",
                  iso639_2t: "eng",
                  iso639_1: "en",
                  scope: "Individual",
                  type_: "Living",
                  name: "English",
                  comment: undefined
                };
                Iso639.Registry.add(registry, entry);
                var found = Iso639.Registry.findByCode(registry, "eng");
                Vitest.expect(found).toEqual(entry);
                var foundByIso1 = Iso639.Registry.findByCode(registry, "en");
                Vitest.expect(foundByIso1).toEqual(entry);
              }));
        Vitest.test("findByName works", (function () {
                var registry = Iso639.Registry.empty();
                var entry = {
                  iso639_3: "deu",
                  iso639_2b: "ger",
                  iso639_2t: "deu",
                  iso639_1: "de",
                  scope: "Individual",
                  type_: "Living",
                  name: "German",
                  comment: undefined
                };
                Iso639.Registry.add(registry, entry);
                var found = Iso639.Registry.findByName(registry, "German");
                Vitest.expect(found).toEqual(entry);
                var foundLower = Iso639.Registry.findByName(registry, "german");
                Vitest.expect(foundLower).toEqual(entry);
              }));
      }));

export {
  
}
/*  Not a pure module */
