// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Statistics from "../../src/utils/Statistics.res.mjs";

function approximately(a, b, toleranceOpt, param) {
  var tolerance = toleranceOpt !== undefined ? toleranceOpt : 0.0001;
  return Math.abs(a - b) < tolerance;
}

Vitest.describe("Statistics.Basic", (function () {
        Vitest.describe("sum", (function () {
                Vitest.test("sums array of floats", (function () {
                        Vitest.expect(Statistics.Basic.sum([
                                    1.0,
                                    2.0,
                                    3.0,
                                    4.0
                                  ])).toBe(10.0);
                      }));
                Vitest.test("returns 0 for empty array", (function () {
                        Vitest.expect(Statistics.Basic.sum([])).toBe(0.0);
                      }));
              }));
        Vitest.describe("mean", (function () {
                Vitest.test("calculates mean correctly", (function () {
                        Vitest.expect(Statistics.Basic.mean([
                                    1.0,
                                    2.0,
                                    3.0,
                                    4.0,
                                    5.0
                                  ])).toBe(3.0);
                      }));
                Vitest.test("returns 0 for empty array", (function () {
                        Vitest.expect(Statistics.Basic.mean([])).toBe(0.0);
                      }));
              }));
        Vitest.describe("variance", (function () {
                Vitest.test("calculates variance correctly", (function () {
                        var result = Statistics.Basic.variance([
                              2.0,
                              4.0,
                              4.0,
                              4.0,
                              5.0,
                              5.0,
                              7.0,
                              9.0
                            ]);
                        Vitest.expect(approximately(result, 4.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("returns 0 for single element", (function () {
                        Vitest.expect(Statistics.Basic.variance([5.0])).toBe(0.0);
                      }));
                Vitest.test("returns 0 for empty array", (function () {
                        Vitest.expect(Statistics.Basic.variance([])).toBe(0.0);
                      }));
              }));
        Vitest.describe("standardDeviation", (function () {
                Vitest.test("calculates standard deviation correctly", (function () {
                        var result = Statistics.Basic.standardDeviation([
                              2.0,
                              4.0,
                              4.0,
                              4.0,
                              5.0,
                              5.0,
                              7.0,
                              9.0
                            ]);
                        Vitest.expect(approximately(result, 2.0, undefined, undefined)).toBe(true);
                      }));
              }));
        Vitest.describe("min and max", (function () {
                Vitest.test("min returns minimum value", (function () {
                        Vitest.expect(Statistics.Basic.min([
                                    3.0,
                                    1.0,
                                    4.0,
                                    1.0,
                                    5.0
                                  ])).toEqual(1.0);
                      }));
                Vitest.test("max returns maximum value", (function () {
                        Vitest.expect(Statistics.Basic.max([
                                    3.0,
                                    1.0,
                                    4.0,
                                    1.0,
                                    5.0
                                  ])).toEqual(5.0);
                      }));
                Vitest.test("min returns None for empty array", (function () {
                        Vitest.expect(Statistics.Basic.min([])).toEqual(undefined);
                      }));
                Vitest.test("max returns None for empty array", (function () {
                        Vitest.expect(Statistics.Basic.max([])).toEqual(undefined);
                      }));
              }));
      }));

Vitest.describe("Statistics.Information", (function () {
        Vitest.describe("entropy", (function () {
                Vitest.test("calculates entropy for uniform distribution", (function () {
                        var dist = [
                          0.25,
                          0.25,
                          0.25,
                          0.25
                        ];
                        var result = Statistics.Information.entropy(dist);
                        Vitest.expect(approximately(result, 2.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("returns 0 for deterministic distribution", (function () {
                        var dist = [
                          1.0,
                          0.0,
                          0.0,
                          0.0
                        ];
                        var result = Statistics.Information.entropy(dist);
                        Vitest.expect(approximately(result, 0.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("handles binary distribution correctly", (function () {
                        var dist = [
                          0.5,
                          0.5
                        ];
                        var result = Statistics.Information.entropy(dist);
                        Vitest.expect(approximately(result, 1.0, undefined, undefined)).toBe(true);
                      }));
              }));
        Vitest.describe("klDivergence", (function () {
                Vitest.test("returns 0 for identical distributions", (function () {
                        var p = [
                          0.25,
                          0.25,
                          0.25,
                          0.25
                        ];
                        var result = Statistics.Information.klDivergence(p, p);
                        Vitest.expect(approximately(result, 0.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("is asymmetric", (function () {
                        var p = [
                          0.5,
                          0.5
                        ];
                        var q = [
                          0.9,
                          0.1
                        ];
                        var kl_pq = Statistics.Information.klDivergence(p, q);
                        var kl_qp = Statistics.Information.klDivergence(q, p);
                        Vitest.expect(kl_pq !== kl_qp).toBe(true);
                      }));
                Vitest.test("returns NaN for mismatched lengths", (function () {
                        var p = [
                          0.5,
                          0.5
                        ];
                        var q = [
                          0.33,
                          0.33,
                          0.34
                        ];
                        var result = Statistics.Information.klDivergence(p, q);
                        Vitest.expect(isNaN(result)).toBe(true);
                      }));
              }));
        Vitest.describe("symmetricKL", (function () {
                Vitest.test("is symmetric", (function () {
                        var p = [
                          0.5,
                          0.5
                        ];
                        var q = [
                          0.9,
                          0.1
                        ];
                        var skl_pq = Statistics.Information.symmetricKL(p, q);
                        var skl_qp = Statistics.Information.symmetricKL(q, p);
                        Vitest.expect(approximately(skl_pq, skl_qp, undefined, undefined)).toBe(true);
                      }));
              }));
        Vitest.describe("jensenShannon", (function () {
                Vitest.test("is symmetric", (function () {
                        var p = [
                          0.5,
                          0.5
                        ];
                        var q = [
                          0.9,
                          0.1
                        ];
                        var js_pq = Statistics.Information.jensenShannon(p, q);
                        var js_qp = Statistics.Information.jensenShannon(q, p);
                        Vitest.expect(approximately(js_pq, js_qp, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("returns 0 for identical distributions", (function () {
                        var p = [
                          0.25,
                          0.25,
                          0.25,
                          0.25
                        ];
                        var result = Statistics.Information.jensenShannon(p, p);
                        Vitest.expect(approximately(result, 0.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("is bounded between 0 and 1", (function () {
                        var p = [
                          1.0,
                          0.0
                        ];
                        var q = [
                          0.0,
                          1.0
                        ];
                        var result = Statistics.Information.jensenShannon(p, q);
                        Vitest.expect(result >= 0.0 && result <= 1.0).toBe(true);
                      }));
              }));
      }));

Vitest.describe("Statistics.Distance", (function () {
        Vitest.describe("euclidean", (function () {
                Vitest.test("calculates euclidean distance correctly", (function () {
                        var a = [
                          0.0,
                          0.0
                        ];
                        var b = [
                          3.0,
                          4.0
                        ];
                        Vitest.expect(Statistics.Distance.euclidean(a, b)).toBe(5.0);
                      }));
                Vitest.test("returns 0 for identical vectors", (function () {
                        var a = [
                          1.0,
                          2.0,
                          3.0
                        ];
                        Vitest.expect(Statistics.Distance.euclidean(a, a)).toBe(0.0);
                      }));
              }));
        Vitest.describe("cosine", (function () {
                Vitest.test("returns 0 for identical vectors", (function () {
                        var a = [
                          1.0,
                          2.0,
                          3.0
                        ];
                        var result = Statistics.Distance.cosine(a, a);
                        Vitest.expect(approximately(result, 0.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("returns 1 for orthogonal vectors", (function () {
                        var a = [
                          1.0,
                          0.0
                        ];
                        var b = [
                          0.0,
                          1.0
                        ];
                        var result = Statistics.Distance.cosine(a, b);
                        Vitest.expect(approximately(result, 1.0, undefined, undefined)).toBe(true);
                      }));
              }));
        Vitest.describe("jaccard", (function () {
                Vitest.test("returns 0 for identical sets", (function () {
                        var a = [
                          1.0,
                          1.0,
                          0.0
                        ];
                        Vitest.expect(Statistics.Distance.jaccard(a, a)).toBe(0.0);
                      }));
                Vitest.test("returns 1 for disjoint sets", (function () {
                        var a = [
                          1.0,
                          0.0,
                          0.0
                        ];
                        var b = [
                          0.0,
                          1.0,
                          1.0
                        ];
                        Vitest.expect(Statistics.Distance.jaccard(a, b)).toBe(1.0);
                      }));
              }));
      }));

Vitest.describe("Statistics.Normalization", (function () {
        Vitest.describe("normalize", (function () {
                Vitest.test("normalizes to sum to 1", (function () {
                        var result = Statistics.Normalization.normalize([
                              1.0,
                              2.0,
                              3.0,
                              4.0
                            ]);
                        var sum = Statistics.Basic.sum(result);
                        Vitest.expect(approximately(sum, 1.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("preserves proportions", (function () {
                        var result = Statistics.Normalization.normalize([
                              1.0,
                              3.0
                            ]);
                        Vitest.expect(approximately(result[0], 0.25, undefined, undefined)).toBe(true);
                        Vitest.expect(approximately(result[1], 0.75, undefined, undefined)).toBe(true);
                      }));
              }));
        Vitest.describe("minMaxNormalize", (function () {
                Vitest.test("scales to [0, 1] range", (function () {
                        var result = Statistics.Normalization.minMaxNormalize([
                              10.0,
                              20.0,
                              30.0
                            ]);
                        Vitest.expect(result[0]).toBe(0.0);
                        Vitest.expect(result[1]).toBe(0.5);
                        Vitest.expect(result[2]).toBe(1.0);
                      }));
              }));
        Vitest.describe("zScoreNormalize", (function () {
                Vitest.test("results in mean of 0", (function () {
                        var result = Statistics.Normalization.zScoreNormalize([
                              1.0,
                              2.0,
                              3.0,
                              4.0,
                              5.0
                            ]);
                        var mean = Statistics.Basic.mean(result);
                        Vitest.expect(approximately(mean, 0.0, undefined, undefined)).toBe(true);
                      }));
                Vitest.test("results in standard deviation of 1", (function () {
                        var result = Statistics.Normalization.zScoreNormalize([
                              1.0,
                              2.0,
                              3.0,
                              4.0,
                              5.0
                            ]);
                        var sd = Statistics.Basic.standardDeviation(result);
                        Vitest.expect(approximately(sd, 1.0, undefined, undefined)).toBe(true);
                      }));
              }));
      }));

export {
  approximately ,
}
/*  Not a pure module */
