// Generated by ReScript, PLEASE EDIT WITH CARE


var version = "0.1.0";

var name = "1000Langs";

var description = "Super-parallel corpus crawler for multilingual NLP research";

var allSources = [
  "BibleCloud",
  "BibleCom",
  "BibleIs",
  "PngScriptures",
  "EBible",
  "FindBible"
];

function sourceToString(source) {
  switch (source) {
    case "BibleCloud" :
        return "bible.cloud";
    case "BibleCom" :
        return "bible.com";
    case "BibleIs" :
        return "bible.is";
    case "PngScriptures" :
        return "pngscriptures.org";
    case "EBible" :
        return "ebible.org";
    case "FindBible" :
        return "find.bible";
    
  }
}

var Config = {
  version: version,
  name: name,
  description: description,
  allSources: allSources,
  sourceToString: sourceToString
};

function make(code, name, family, script, country, param) {
  return {
          code: code,
          name: name,
          family: family,
          script: script,
          country: country
        };
}

function getCode(lang) {
  return lang.code;
}

function getName(lang) {
  return lang.name;
}

var Language = {
  make: make,
  getCode: getCode,
  getName: getName
};

function makeReference(book, chapter, verse) {
  return {
          book: book,
          chapter: chapter,
          verse: verse
        };
}

function make$1(reference, text, language) {
  return {
          reference: reference,
          text: text,
          language: language
        };
}

function toCanonicalId(ref) {
  return ref.book + "." + ref.chapter.toString() + "." + ref.verse.toString();
}

var Verse = {
  makeReference: makeReference,
  make: make$1,
  toCanonicalId: toCanonicalId
};

function empty(name) {
  return {
          name: name,
          languages: [],
          alignments: [],
          metadata: {}
        };
}

function addLanguage(corpus, lang) {
  return {
          name: corpus.name,
          languages: corpus.languages.concat([lang]),
          alignments: corpus.alignments,
          metadata: corpus.metadata
        };
}

function addAlignment(corpus, alignment) {
  return {
          name: corpus.name,
          languages: corpus.languages,
          alignments: corpus.alignments.concat([alignment]),
          metadata: corpus.metadata
        };
}

function languageCount(corpus) {
  return corpus.languages.length;
}

function alignmentCount(corpus) {
  return corpus.alignments.length;
}

var Corpus = {
  empty: empty,
  addLanguage: addLanguage,
  addAlignment: addAlignment,
  languageCount: languageCount,
  alignmentCount: alignmentCount
};

function main() {
  console.log(name + " v" + version);
  console.log(description);
  console.log("Supported sources: " + allSources.map(sourceToString).join(", "));
}

main();

export {
  Config ,
  Language ,
  Verse ,
  Corpus ,
  main ,
}
/*  Not a pure module */
